### ISSUE TITLE
 java.io.FileNotFoundException: ./assets/server_config.leola (No such file or directory)

### ISSUE THREAD

**Issue by pikapikapii** [tonysparks/seventh#33]
when i tried to run server in intellij , window opens and shows this message ,but i cannot find the  specific file(./assets/server_config.leola) the program is asking for

**Comment by pikapikapii** [comment]
i tried seventh-0.4.1-beta version

**Comment by pikapikapii** [comment]
sorry to ask this kind of question, i just found the assets file

**Comment by tonysparks** [comment]
Am I good to close this issue?

**Comment by pikapikapii** [comment]
> Am I good to close this issue?

yes
